weight = float(input("Enter your weight in kilograms "))
height = float(input("Enter your height in meters "))
bmi = weight / (height ** 2)
print(f"Your BMI is: {bmi:.2f}")
print("BMI Categories:")
print("Underweight = <18.5")
print("Normal Weight = 18.5 to 24.9")
print("Overweight = 25 to 29.9")
print("Obesity = BMI of 30 or greater")